// Seed data extracted from the master accounts spreadsheet
export const SEED_ACCOUNTS = [
  // ── Anuales ────────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'January',
    paymentMethod: 'Cash',
    code: '',
    name: 'Impuestos (Casa QT) (enero, febrero)',
    description: 'Impuestos (Casa QT) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Impuestos (Apt Milgrosa) (enero, febrero)',
    description: 'Impuestos (Apt Milgrosa) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Impuestos (Apt Milgrosa, cuarto util) (enero, febrero)',
    description: 'Impuestos (Apt Milgrosa, cuarto util) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Impuesto Antioquia KMR636, Enero a Abril',
    description: 'Impuesto Municipal Envigado KMR636, Enero a Abril',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Semaforización KMR636 (Febrero)',
    description: 'Semaforización (Febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'April',
    paymentMethod: 'Cash',
    code: '',
    name: 'SOAT KMR636 * (Abril)',
    description: 'SOAT * (Abril)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'April',
    paymentMethod: 'Cash',
    code: '',
    name: 'Revisión Tecnomecánica KMR636 (RTM) * (Abril)',
    description: 'Revisión Tecnomecánica (RTM) * (Abril)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'October',
    paymentMethod: 'Cash',
    code: '',
    name: 'Impuestos DIAN* (Semptiembre, Octubre) declaración',
    description: 'Impuestos DIAN* (Semptiembre, Octubre)',
    active: true,
  },

  // ── N/A ────────────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Salarios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Fabian',
    description: 'Fabian',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Prestamos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Carmen',
    description: 'Carmen',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Ayudas',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Yessica',
    description: 'Yessica',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Prestamos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Romer',
    description: 'Romer',
    active: true,
  },

  // ── Mensuales ──────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Ocasionales',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Expensas (Almacen) a mediano y largo plazo',
    description: 'Expensas (Almacen) a mediano y largo plazo',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Ocio',
    description: 'Ocio',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ayudas',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Sofía, Guadalupe',
    description: 'Altruismo Sofía, Mariana, Fabiola, Perritos, Guadalupe',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Ocasionales',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Gastos Ocasionales (Carro, casas, salud, etc...)',
    description: 'Gastos Ocasionales (Carro, casas, salud, etc...)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Transporte',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Deel Card',
    code: '',
    name: 'Gasolina, Transportes y Peajes',
    description: 'Gasolina, Transportes y Peajes',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Alimentación',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Deel Card',
    code: '',
    name: 'Mercado (Comida, Alimentos mes)',
    description: 'Mercado (Comida, Alimentos mes)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Servicios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Plan celular',
    description: 'Plan celular',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Servicios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Internet Finca',
    description: 'Internet Finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Fijos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Gas Finca *',
    description: 'Gas Finca *',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Servicios',
    maxDatePay: 5,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Servicios Finca EPM',
    description: 'Servicios Finca EPM',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Fijos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Agua finca',
    description: 'Agua finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Gastos Fijos',
    maxDatePay: 5,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Alquiler Finca',
    description: 'Alquiler Finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Tv Prime',
    description: 'Tv Prime',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Youtube Premium',
    description: 'Youtube Premium',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Gastos Fijos',
    maxDatePay: 30,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '',
    name: 'Administración (Apt Milagrosa) *',
    description: 'Administración (Apt Milagrosa) *',
    active: true,
  },
]
