// Seed data extracted from the master accounts spreadsheet
export const SEED_ACCOUNTS = [
  // ── Anuales ────────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'January',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Impuesto predial — Vivienda 1',
    name: 'Impuestos (Casa QT) (enero, febrero)',
    description: 'Impuestos (Casa QT) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Impuesto predial — Vivienda 2',
    name: 'Impuestos (Apt Milgrosa) (enero, febrero)',
    description: 'Impuestos (Apt Milgrosa) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Impuesto predial — Local comercial',
    name: 'Impuestos (Apt Milgrosa, cuarto util) (enero, febrero)',
    description: 'Impuestos (Apt Milgrosa, cuarto util) (enero, febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Impuesto de rodamiento vehicular',
    name: 'Impuesto Antioquia KMR636, Enero a Abril',
    description: 'Impuesto Municipal Envigado KMR636, Enero a Abril',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Derechos de tránsito y circulación',
    name: 'Semaforización KMR636 (Febrero)',
    description: 'Semaforización (Febrero)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'April',
    paymentMethod: 'Cash',
    code: '5130',
    accountingName: 'Seguro obligatorio de accidentes — SOAT',
    name: 'SOAT KMR636 * (Abril)',
    description: 'SOAT * (Abril)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'April',
    paymentMethod: 'Cash',
    code: '5145',
    accountingName: 'Mantenimiento y revisión vehicular',
    name: 'Revisión Tecnomecánica KMR636 (RTM) * (Abril)',
    description: 'Revisión Tecnomecánica (RTM) * (Abril)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Anuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Impuestos',
    maxDatePay: 15,
    monthStartAt: 'October',
    paymentMethod: 'Cash',
    code: '5115',
    accountingName: 'Impuesto de renta — Declaración DIAN',
    name: 'Impuestos DIAN* (Semptiembre, Octubre) declaración',
    description: 'Impuestos DIAN* (Semptiembre, Octubre)',
    active: true,
  },

  // ── N/A ────────────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Salarios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5110',
    accountingName: 'Honorarios — servicios personales',
    name: 'Fabian',
    description: 'Fabian',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Prestamos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Préstamos a terceros — amortización',
    name: 'Carmen',
    description: 'Carmen',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Ayudas',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Donaciones y ayudas a terceros',
    name: 'Yessica',
    description: 'Yessica',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'N/A',
    definition: 'N/A',
    classification: 'dispensable',
    category: 'Prestamos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Préstamos a terceros — amortización',
    name: 'Romer',
    description: 'Romer',
    active: true,
  },

  // ── Mensuales ──────────────────────────────────────────────────────────────
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Ocasionales',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos diferidos — expensas',
    name: 'Expensas (Almacen) a mediano y largo plazo',
    description: 'Expensas (Almacen) a mediano y largo plazo',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos de entretenimiento y recreación',
    name: 'Ocio',
    description: 'Ocio',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ayudas',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Donaciones y ayudas a terceros',
    name: 'Sofía, Guadalupe',
    description: 'Altruismo Sofía, Mariana, Fabiola, Perritos, Guadalupe',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Ocasionales',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos generales diversos',
    name: 'Gastos Ocasionales (Carro, casas, salud, etc...)',
    description: 'Gastos Ocasionales (Carro, casas, salud, etc...)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Transporte',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Deel Card',
    code: '5155',
    accountingName: 'Gastos de movilización y transporte',
    name: 'Gasolina, Transportes y Peajes',
    description: 'Gasolina, Transportes y Peajes',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Alimentación',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Deel Card',
    code: '5195',
    accountingName: 'Gastos de alimentación',
    name: 'Mercado (Comida, Alimentos mes)',
    description: 'Mercado (Comida, Alimentos mes)',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Servicios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5135',
    accountingName: 'Servicios de telecomunicaciones — móvil',
    name: 'Plan celular',
    description: 'Plan celular',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Servicios',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5135',
    accountingName: 'Servicios de telecomunicaciones — internet',
    name: 'Internet Finca',
    description: 'Internet Finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Fijos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5135',
    accountingName: 'Servicios públicos — gas',
    name: 'Gas Finca *',
    description: 'Gas Finca *',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Servicios',
    maxDatePay: 5,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5135',
    accountingName: 'Servicios públicos — energía eléctrica',
    name: 'Servicios Finca EPM',
    description: 'Servicios Finca EPM',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Gastos Fijos',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5135',
    accountingName: 'Servicios públicos — acueducto',
    name: 'Agua finca',
    description: 'Agua finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Gastos Fijos',
    maxDatePay: 5,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5120',
    accountingName: 'Arrendamientos — inmueble',
    name: 'Alquiler Finca',
    description: 'Alquiler Finca',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos de entretenimiento — streaming',
    name: 'Tv Prime',
    description: 'Tv Prime',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'dispensable',
    category: 'Ocio',
    maxDatePay: 15,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos de entretenimiento — streaming',
    name: 'Youtube Premium',
    description: 'Youtube Premium',
    active: true,
  },
  {
    type: 'Outcoming',
    period: 'Mensuales',
    definition: 'Indefinidos',
    classification: 'indispensable',
    category: 'Gastos Fijos',
    maxDatePay: 30,
    monthStartAt: 'February',
    paymentMethod: 'Cash',
    code: '5195',
    accountingName: 'Gastos de administración — cuota propiedad horizontal',
    name: 'Administración (Apt Milagrosa) *',
    description: 'Administración (Apt Milagrosa) *',
    active: true,
  },
]

// Patch table: maps existing account names → PUC code + accounting name (NIIF)
// Used by the "Actualizar nombres contables" button in AccountsMaster
export const PATCH_ACCOUNTING = [
  {
    name: 'Impuestos (Casa QT) (enero, febrero)',
    code: '5115',
    accountingName: 'Impuesto predial — Vivienda 1',
  },
  {
    name: 'Impuestos (Apt Milgrosa) (enero, febrero)',
    code: '5115',
    accountingName: 'Impuesto predial — Vivienda 2',
  },
  {
    name: 'Impuestos (Apt Milgrosa, cuarto util) (enero, febrero)',
    code: '5115',
    accountingName: 'Impuesto predial — Local comercial',
  },
  {
    name: 'Impuesto Antioquia KMR636, Enero a Abril',
    code: '5115',
    accountingName: 'Impuesto de rodamiento vehicular',
  },
  {
    name: 'Semaforización KMR636 (Febrero)',
    code: '5115',
    accountingName: 'Derechos de tránsito y circulación',
  },
  {
    name: 'SOAT KMR636 * (Abril)',
    code: '5130',
    accountingName: 'Seguro obligatorio de accidentes — SOAT',
  },
  {
    name: 'Revisión Tecnomecánica KMR636 (RTM) * (Abril)',
    code: '5145',
    accountingName: 'Mantenimiento y revisión vehicular',
  },
  {
    name: 'Impuestos DIAN* (Semptiembre, Octubre) declaración',
    code: '5115',
    accountingName: 'Impuesto de renta — Declaración DIAN',
  },
  { name: 'Fabian', code: '5110', accountingName: 'Honorarios — servicios personales' },
  { name: 'Carmen', code: '5195', accountingName: 'Préstamos a terceros — amortización' },
  { name: 'Yessica', code: '5195', accountingName: 'Donaciones y ayudas a terceros' },
  { name: 'Romer', code: '5195', accountingName: 'Préstamos a terceros — amortización' },
  {
    name: 'Expensas (Almacen) a mediano y largo plazo',
    code: '5195',
    accountingName: 'Gastos diferidos — expensas',
  },
  { name: 'Ocio', code: '5195', accountingName: 'Gastos de entretenimiento y recreación' },
  { name: 'Sofía, Guadalupe', code: '5195', accountingName: 'Donaciones y ayudas a terceros' },
  {
    name: 'Gastos Ocasionales (Carro, casas, salud, etc...)',
    code: '5195',
    accountingName: 'Gastos generales diversos',
  },
  {
    name: 'Gasolina, Transportes y Peajes',
    code: '5155',
    accountingName: 'Gastos de movilización y transporte',
  },
  {
    name: 'Mercado (Comida, Alimentos mes)',
    code: '5195',
    accountingName: 'Gastos de alimentación',
  },
  { name: 'Plan celular', code: '5135', accountingName: 'Servicios de telecomunicaciones — móvil' },
  {
    name: 'Internet Finca',
    code: '5135',
    accountingName: 'Servicios de telecomunicaciones — internet',
  },
  { name: 'Gas Finca *', code: '5135', accountingName: 'Servicios públicos — gas' },
  {
    name: 'Servicios Finca EPM',
    code: '5135',
    accountingName: 'Servicios públicos — energía eléctrica',
  },
  { name: 'Agua finca', code: '5135', accountingName: 'Servicios públicos — acueducto' },
  { name: 'Alquiler Finca', code: '5120', accountingName: 'Arrendamientos — inmueble' },
  { name: 'Tv Prime', code: '5195', accountingName: 'Gastos de entretenimiento — streaming' },
  {
    name: 'Youtube Premium',
    code: '5195',
    accountingName: 'Gastos de entretenimiento — streaming',
  },
  {
    name: 'Administración (Apt Milagrosa) *',
    code: '5195',
    accountingName: 'Gastos de administración — cuota propiedad horizontal',
  },
]
