export const PROGRAM_HOOKS = [
  { key: 'user.create', label: 'Usuario — crear' },
  { key: 'user.update', label: 'Usuario — actualizar' },
  { key: 'user.delete', label: 'Usuario — eliminar' },
  { key: 'driver.create', label: 'Conductor — crear' },
  { key: 'driver.update', label: 'Conductor — actualizar' },
  { key: 'driver.delete', label: 'Conductor — eliminar' },
  { key: 'vehicle.create', label: 'Vehículo — crear' },
  { key: 'vehicle.update', label: 'Vehículo — actualizar' },
  { key: 'vehicle.delete', label: 'Vehículo — eliminar' },
  { key: 'settlement.create', label: 'Liquidación — crear' },
  { key: 'settlement.update', label: 'Liquidación — actualizar' },
  { key: 'settlement.delete', label: 'Liquidación — eliminar' },
  { key: 'expense.create', label: 'Gasto — crear' },
  { key: 'expense.update', label: 'Gasto — actualizar' },
  { key: 'expense.delete', label: 'Gasto — eliminar' },
  { key: 'partner.create', label: 'Socio — crear' },
  { key: 'partner.update', label: 'Socio — actualizar' },
  { key: 'partner.delete', label: 'Socio — eliminar' },
  { key: 'payment.create', label: 'Pago — crear' },
  { key: 'payment.update', label: 'Pago — actualizar' },
  { key: 'payment.delete', label: 'Pago — eliminar' },
  { key: 'transaction.create', label: 'Transacción — crear' },
  { key: 'transaction.update', label: 'Transacción — actualizar' },
  { key: 'transaction.delete', label: 'Transacción — eliminar' },
]
